Added more youtubers
collab-community/coding-youtubers pull request #26
Opened 2022-08-05 03:25 UTC by fluentmoheshwar

2022-08-05 03:51 UTC, Adarsh-jaiss approved these changes

2022-08-05 03:52 UTC, Adarsh-jaiss approved these changes

2022-08-05 03:53 UTC, Adarsh-jaiss approved these changes

2022-08-05 03:53 UTC, Adarsh-jaiss approved these changes

2022-08-05 03:53 UTC, Adarsh-jaiss commented
-- @KendallDoesCoding  review it ASAP!

2022-08-05 07:58 UTC, KendallDoesCoding commented
@Adarsh-jaiss , how much you approved man.

2022-08-05 07:59 UTC, KendallDoesCoding commented
If you were fine, you could've bypassed the merge without requiring requirements to be met and merged, didn't have to approve so much lol

2022-08-05 08:00 UTC, KendallDoesCoding requested changes

2022-08-05 08:00 UTC, KendallDoesCoding commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
```suggestion
- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel will give you project ideas, how to learn something such as **Web Development** or **Game Development** and some motivation.
```

remove "This channel is weird", no content is weird.

2022-08-05 08:25 UTC, KendallDoesCoding commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
Can we inculde This channel makes content around to follow the theme of the other sentences?

2022-08-07 15:46 UTC, KendallDoesCoding commented
@fluentmoheshwar Please commit requested changes at the earliest.

2022-08-07 17:33 UTC, AnimeshKumar923 commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
If you want uniformity, you can go with "This channel makes content around..."

2022-08-07 17:35 UTC, KendallDoesCoding commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
> If you want uniformity, you can go with "This channel makes content around..."

Yes but it won't work if it's, This channel make's content around project ideas.

@fluentmoheshwar I suggest to make it as follows:

```
This channel makes content around **Web Development** and **Game Development**, they also give motivation and project ideas.

```

What do you think @AnimeshKumar923

2022-08-07 17:37 UTC, AnimeshKumar923 commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
Looks good 👍🏻

2022-08-07 17:37 UTC, AnimeshKumar923 commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
Also remove the wierd word @KendallDoesCoding

2022-08-07 17:39 UTC, KendallDoesCoding commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
> Also remove the wierd word, no prejudices. @KendallDoesCoding

Yes, I have created a suggestion in my review to do so (scroll up)

2022-08-07 17:40 UTC, AnimeshKumar923 commented on README.md
> +- [Programming Hero](https://www.youtube.com/c/ProgrammingHero) - This channel is weird. This channel will give you project ideas, how to learn something such as **Web Development** or **Game Develop
Ah, ok, that's good.

2022-08-12 07:31 UTC, fluentmoheshwar commented
@KendallDoesCoding closed due to merge conflict

2022-08-12 07:31 UTC, closed without merging

2022-08-12 07:45 UTC, fluentmoheshwar commented
@KendallDoesCoding check #48