Updated with JavaScript Mastery channel
collab-community/coding-youtubers pull request #34
Opened 2022-08-07 16:55 UTC by LimitlessUR

Hello! I added a channel that has helped me come a long way in JS. I am also new to collaboration. Please let me know if I missed something. Thank you

2022-08-07 17:07 UTC, KendallDoesCoding requested changes
the "and" doesn't have to be bold.

2022-08-07 17:07 UTC, KendallDoesCoding commented on README.md
> +| [Javascript Mastery](https://www.youtube.com/c/JavaScriptMastery) | Produces great content related to **Javascript Web Development and Application Development** | English |
```suggestion
| [Javascript Mastery](https://www.youtube.com/c/JavaScriptMastery) | Produces great content related to **Javascript Web Development** and **Application Development** | English |
```

2022-08-07 23:31 UTC, LimitlessUR commented
Great catch sounds great. Thank you

On Sun, Aug 7, 2022 at 11:07 AM Kendall ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> the "and" doesn't have to be bold.
> ------------------------------
>
> In README.md
> <https://github.com/collab-community/coding-youtubers/pull/34#discussion_r939696560>
> :
>
> > @@ -37,3 +37,4 @@ If you're a YouTuber reading this and if you think you make beginner-friendly tu
>
>  | [Procoder](https://www.youtube.com/c/ProcoderBD) | Makes content around **Web Development** | Bengali |
>
>  | [JS Bangladesh](https://www.youtube.com/c/JSBangladesh) | Makes content around **Web Development** but focuses mostly on **Javascript** | Bengali |
>
>  | [Anisul Islam](https://www.youtube.com/c/anisulislamrubel) | Mostly makes content around **Web Development** but also makes discussion videos & content around other programming languages from time to time | Bengali |
>
> +| [Javascript Mastery](https://www.youtube.com/c/JavaScriptMastery) | Produces great content related to **Javascript Web Development and Application Development** | English |
>
>
> ⬇️ Suggested change
>
> -| [Javascript Mastery](https://www.youtube.com/c/JavaScriptMastery) | Produces great content related to **Javascript Web Development and Application Development** | English |
>
> +| [Javascript Mastery](https://www.youtube.com/c/JavaScriptMastery) | Produces great content related to **Javascript Web Development** and **Application Development** | English |
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/collab-community/coding-youtubers/pull/34#pullrequestreview-1064448312>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUUIYCFC435S6KDUR2M4XJLVX7UMFANCNFSM552X3N7A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-08 06:23 UTC, KendallDoesCoding approved these changes

2022-08-08 06:24 UTC, KendallDoesCoding commented
Thanks for your contribution @LimitlessUR!, merging.

2022-08-08 06:24 UTC, merged

2022-10-11 08:52 UTC, LimitlessUR commented
Thank you :)

On Mon, Aug 8, 2022 at 12:24 AM Kendall ***@***.***> wrote:

> Merged #34 <https://github.com/collab-community/coding-youtubers/pull/34>
> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/collab-community/coding-youtubers/pull/34#event-7144162453>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUUIYCF3NYOAM3V3IXWFK7TVYCRZFANCNFSM552X3N7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>