These channels helped me to level up my Front End Skills
collab-community/coding-youtubers pull request #46
Opened 2022-08-10 02:42 UTC by SojinSamuel

These channels explain js, angular, react, and typescript in a solid way + it's presented in an easy-to-digest format for absolute beginners who are starting out their coding journey

2022-08-10 07:45 UTC, KendallDoesCoding reviewed
The description scheme is not like the above ones and needs a little shortning which I will help you with in a bit. Other then that, looks good

2022-08-12 08:03 UTC, KendallDoesCoding requested changes

2022-08-12 08:03 UTC, KendallDoesCoding commented on README.md
> +| [Kent C. Dodds](https://www.youtube.com/user/kentdoddsfamily/videos) | In this YouTube channel, you’ll find live streams and videos on beginner and advanced topics ranging from **JavaScript** to **
```suggestion
| [Kent C. Dodds](https://www.youtube.com/user/kentdoddsfamily/videos) | Makes content around **JavaScript**, **React**, **TypeScript**, and **dev tips** | English |
```

2022-08-12 08:03 UTC, KendallDoesCoding commented on README.md
> +| [Double South](https://www.youtube.com/channel/UCzroHLKLlfA-hR7S4if6qww) | In this channel, Itsey teaches **beginner friendly** JavaScript, HTML, and CSS | Pidgin English |
```suggestion
| [Double South](https://www.youtube.com/channel/UCzroHLKLlfA-hR7S4if6qww) | Makes content around **beginner friendly** JavaScript, HTML, and CSS | Pidgin English |
```

2022-08-12 08:03 UTC, KendallDoesCoding commented on README.md
> +| [The New Boston](https://www.youtube.com/user/thenewboston) | This channel provides tutorials in abundance for the following sub-topics – **ReactJS**, **ES6** (ECMA Script), **AngularJS**, Working
```suggestion
| [The New Boston](https://www.youtube.com/user/thenewboston) | Makes content around **ReactJS**, **ES6** (ECMA Script), **AngularJS**, Working with **NodeJS**, **Vanilla JavaScript** and **Docker**| English |
```

2022-08-12 08:03 UTC, KendallDoesCoding commented on README.md
> +| [LearnCode.academy](https://www.youtube.com/c/learncodeacademy/videos) | This channel provides tutorials on everything you need to kick start your **web development** journey, but not limited to Ja
```suggestion
| [LearnCode.academy](https://www.youtube.com/c/learncodeacademy/videos) |Makes content around **web development**.| English |
```

2022-08-12 08:03 UTC, KendallDoesCoding commented on README.md
> +| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript,
```suggestion
| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, Nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript, focusing on Distributed Systems hosted on the cloud. | English |
```

2022-08-12 08:03 UTC, KendallDoesCoding commented on README.md
> +| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript,
I don't know what edits we can make to this line to make it shorter, any ideas @AnimeshKumar923 https://github.com/orgs/collab-community/teams/coding-youtubers?

2022-08-12 09:14 UTC, AnimeshKumar923 commented on README.md
> +| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript,
> I don't know what edits we can make to this line to make it shorter, any ideas @AnimeshKumar923 https://github.com/orgs/collab-community/teams/coding-youtubers?


You can assign it to me. I'll look into it after sometimea nd fix everything.

A bit busy with college stuff...😅

2022-08-12 10:04 UTC, KendallDoesCoding commented on README.md
> +| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript,
Ok cool, I think my changes are good for the other ones, but struggling for edits with line 47 lol

2022-08-12 10:10 UTC, AnimeshKumar923 commented on README.md
> +| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript,
> Ok cool, I think my changes are good for the other ones, but struggling for edits with line 47 lol

Don't merge this pr, keep it open.

I have some new ideas which I'll be sharing tonight and will be of great help.

Just let me finish this college work...🗿

2022-08-12 10:13 UTC, KendallDoesCoding commented on README.md
> +| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript,
> > Ok cool, I think my changes are good for the other ones, but struggling for edits with line 47 lol
> 
> Don't merge this pr, keep it open.
> 
> I have some new ideas which I'll be sharing tonight and will be of great help.
> 
> Just let me finish this college work...🗿

Yeah, I was anyway merge only once @SojinSamuel commit's my requested changes, I'll keep it open till your reply!

2022-08-12 10:15 UTC, AnimeshKumar923 commented on README.md
> +| [Amigoscode](https://www.youtube.com/c/amigoscode) | In the past few years, nelson has programmed in various programming languages such as PHP, Python, C# and primarily writes Java and JavaScript,
Thank you for your patience....

2022-08-17 16:22 UTC, merged

2022-08-17 16:22 UTC, adityajoshi-08 commented
Thanks for the contribution Samuel!